---
title: "US Gun Murders"
author: "Subhendu Mahapatro"
date: "29-03-2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This is a report on 2010 gun murder rates obtained from FBI reports. The original data was obtained from [this Wikipedia page](https://en.wikipedia.org/wiki/Murder_in_the_United_States_by_state).

We are going to use the following library:

```{r loading-libs, message=FALSE}
library(tidyverse)
```
  
and load the data we already wrangled:

```{r}
load("rda/murders.rda")
```

## Murder rate by state 

We note the large state to state variability by generating a barplot showing the murder rate by state:

```{r murder-rate-by-state, echo=FALSE}
murders %>% mutate(abb = reorder(abb, rate)) %>%
  ggplot(aes(abb, rate, color = cut(rate, quantile(rate)))) +
  geom_bar(width = 0.5, stat = "identity") +
  coord_flip() + 
  labs(color = "Range", x = "State", y = "Murders per 100,000", title = "US Gun Murders 2010")
```
